name: dic-nico-intersection-pixiv
version: 0.1.0.0
category: Language
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT
github: ncaq/dic-nico-intersection-pixiv

language: GHC2021

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -O2
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

dependencies:
  - base >=4.7 && <5
  - async
  - attoparsec
  - bytestring
  - containers
  - convertible
  - directory
  - hashable
  - http-conduit
  - http-types
  - parallel
  - retry
  - scalpel
  - store
  - text
  - text-icu-translit
  - text-metrics
  - time
  - unicode-transforms
  - unordered-containers
  - xml-conduit
  - pretty-simple # for debug

executables:
  dic-nico-intersection-pixiv:
    main: Main.hs
    source-dirs: src
