name: dic-nico-intersection-pixiv
version: 0.1.0
category: Language
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: PublicDomain
github: ncaq/dic-nico-intersection-pixiv

ghc-options:
  - -Wall
  # - -Wall-missed-specialisations
  - -Widentities
  # - -Wimplicit-prelude
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissed-specialisations
  # - -Wmissing-export-lists
  - -Wmissing-exported-signatures
  - -Wmissing-home-modules
  # - -Wmissing-import-lists
  # - -Wmissing-local-signatures
  # - -Wmonomorphism-restriction
  # - -Wpartial-fields
  - -Wredundant-constraints
  - -Wcompat
  - -O2
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

dependencies:
  - base >=4.7 && <5
  - async
  - bytestring
  - containers
  - directory
  - dom-selector
  - hashable
  - html-conduit
  - http-conduit
  - http-types
  - parallel
  - regex-tdfa
  - store
  - string-transform
  - text
  - text-icu-translit
  - text-metrics
  - time
  - unicode-transforms
  - unordered-containers
  - xml-conduit

executables:
  dic-nico-intersection-pixiv:
    main: Main.hs
    source-dirs: src
