name: dic-nico-intersection-pixiv
version: 0.0.1
category: Language
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: PublicDomain
github: ncaq/dic-nico-intersection-pixiv.git
default-extensions:
- OverloadedStrings
dependencies:
- base >=4.7 && <5
- bytestring
- http-conduit
- http-types
- text
- text-icu
- zip-archive
executables:
  dic-nico-intersection-pixiv:
    main: Main.hs
    source-dirs: src
