name: dic-nico-intersection-pixiv
version: 0.0.1
category: Language
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: PublicDomain
github: ncaq/dic-nico-intersection-pixiv
dependencies:
- base >=4.7 && <5
- containers
- dom-selector
- html-conduit
- http-conduit
- http-types
- string-transform
- text
- time
- unicode-transforms
- xml-conduit
- zip-archive
executables:
  dic-nico-intersection-pixiv:
    main: Main.hs
    source-dirs: src
